# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'Searcher' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Searcher
  pod 'RealmSwift'
  pod 'ARSLineProgress', '~> 1.0'

  target 'SearcherTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SearcherUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
